language: r
r: 
# - 3.6.1
 - devel
dist: xenial
services:
  - xvfb
cache:
  packages: true
  directories:
    - _bookdown_files
    - $HOME/.npm
    
latex: false
pandoc_version: 2.7.2

env:
  global:
    - MAKEFLAGS="-j 2"

repos:
  CRAN: https://cloud.r-project.org
  RForge: https://r-forge.r-project.org

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/ffmpeg-4'
    packages:
      - ghostscript
      - imagemagick
      - optipng
      - graphviz
      - cargo
      - libavdevice-dev
      - libavfilter-dev
      # magick
      - libmagick++-dev
      # pdftools
      - libpoppler-cpp-dev
      # rgl
      - libglu1-mesa-dev
      - libnlopt-dev
      - graphviz
      # sf
      - libudunits2-dev	
      - libproj-dev 	
      - libgeos-dev 	
      - libgdal-dev
      - ggobi
      - libgtk2.0-dev

before_script:
  - mkdir -p ~/.R ~/.fonts
  - curl -fLo /tmp/tinytex.tar.gz https://travis-bin.yihui.org/tinytex.tar.gz
  - tar -xzf /tmp/tinytex.tar.gz -C $HOME
  - export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH
  - tlmgr update --self --all  
  - tlmgr install ctex xecjk mdwtools zhnumber ulem ms xcolor unicode-math filehook lm-math
      subfig sourcecodepro sourceserifpro sourcesanspro cancel titlepic pgf preview psnfss
      jknapltx titlesec tocbibind tocloft trimspaces savesym environ fancyhdr listings
      psnfss realscripts relsize rsfs setspace soul xltxtra mathdesign
  - curl -fLo Adobe-Fonts.zip https://github.com/XiangyunHuang/fonts/releases/download/v0.1/Adobe-Fonts.zip
  - unzip Adobe-Fonts.zip -d ~/.fonts/adobe
  - fc-cache -fsv
  - Rscript -e "sessionInfo(.packages(T));capabilities()"
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE)'
  - Rscript -e 'library(tikzDevice);tikzTest();tikzTest("$\\sin(x^2/2 - y^2/4 + 3) \\cos(2 x + 1 - \\exp(y))$")'

script:
  - mkdir -p _book/interactives && cp -r interactives/* _book/interactives
  - Rscript -e 'bookdown::render_book("index.Rmd")'

after_success:
  - npm install netlify-cli -g
  # deploy with messages 
  - export COMMIT_MSG=$(git log -1 --format='%h %<(50,trunc)%s')
  - echo $COMMIT_MSG
  - export DEPLOY_MSG=${COMMIT_MSG//[\'\"\`]/}
  - echo $DEPLOY_MSG

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
